### ISSUE TITLE
Es gibt nur einen Senf

### ISSUE THREAD

**Issue by glemmal** [danieldiekmeier/HTW-Datenbanken#1]
Hallo Liebes HTW-Datenbanken Team,

leider gibt es tatsächlich nur eine Sorte von Senf die für dieses Unterfangen für geeignet scheint und das ist der süße. Ich bin enttäuscht dass meine Bemühungen des letzten Jahres keine Früchte tragen konnten. Wollen wir das Sortiment mit weiteren Wurstspezialitäten erweitern? Dann würde das in der Tat sehr interessante Konzept dieses Projektes wieder stimmen.

**Comment by danieldiekmeier** [comment]
Das war auch mein Gedankengang, als ich Roberts Text gelesen habe. Möglicherweise kann man das ein bisschen ausgleichen, indem man den Kompatibilitätswert jedes Senfs, der nicht der original Händlmaier-Senf ist, auf 0 setzt.

**Comment by glemmal** [comment]
![haendlmaiers-suesser-hausmachersenf haendlmaiers](https://cloud.githubusercontent.com/assets/2098462/4873856/2cdcbde4-622a-11e4-9e11-39068f2e919e.jpg)
